$(document).ready(function(){
    $(".serv1").click(function(){
        $(".designimg").toggle();
        $(".design").toggle();
    });
    $(".serv2").click(function(){
        $(".devpimg").toggle();
        $(".devp").toggle();
    });
});